before:
  hooks:
    - go mod tidy -v
builds:
  - id: universal
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/agent
    binary: fake-nezha-agent
universal_binaries:
  - name_template: "fake-nezha-agent"
    replace: false
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "fake-nezha-agent"
archives:
  - name_template: "fake-nezha-agent_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
